replicaCount: 2

image:
  repository: norphel/simple-website
  tag: latest
  pullPolicy: IfNotPresent

service:
  name: simple-website
  type: ClusterIP
  port: 80
  targetPort: 3000

gateway:
  enabled: true
  name: nginx-gateway # Name of your existing Gateway
  namespace: simple-website # Namespace where your Gateway is
  host: simple-website-pc.o.selise.dev
