name: Build & Push Docker Image

on:
  workflow_dispatch: # manual trigger

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    environment: dev

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build Docker image
        run: |
          docker build -t ${{vars.DOCKERHUB_USERNAME}}/simple-website:latest ./apps

      - name: Push Docker image
        run: |
          docker push ${{vars.DOCKERHUB_USERNAME}}/simple-website:latest
