apiVersion: gateway.networking.k8s.io/v1beta1
kind: HTTPRoute
metadata:
  name: simple-website
  namespace: {{ .Values.gateway.namespace }}
spec:
  parentRefs:
    - name: {{ .Values.gateway.name }}
  hostnames:
    - {{ .Values.gateway.host | quote }}
  rules:
    - matches:
        - path:
            type: Prefix
            value: /
      backendRefs:
        - name: simple-website
          port: 80
